title: ABsurdly Goud
description: Alex Blake-Goudemond's personal website

url: "https://absurdlygoud.com"

repository: alexBlakeGoudemond/absurdly-goud

excerpt_separator: ---more---

permalink: /:year/:month/:day/:title/

exclude:
  - .ai-playbook/
  - docker/
  - docs/
  - absurdly-goud-obsidian/
  - AGENTS.md
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - Makefile
  - README.md

plugins:
  - jekyll-paginate

paginate: 3
paginate_path: "/posts/page:num/"

# default frontmatter for all
defaults:

  # anything inside posts gets this layout frontmatter
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

  # set the page.author liquid variable for all files
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      author: "alexBlakeGoudemond"

  # all files in the assets/images folder have frontmatter variable `image` set to true
  - scope:
      path: "assets/images"
    values:
      image: true