version: "3.8"

services:

  jekyll:
    build:
      context: ..
      dockerfile: docker/ruby/Dockerfile

    working_dir: /workbench

    volumes:
      - ..:/workbench
      - ai_playbook_stub:/workbench/.ai-playbook:ro

    ports:
      - "4000:4000"

    command: ["/usr/local/bin/entrypoint.sh"]

volumes:
  ai_playbook_stub: {}